# Generated by Django 5.2.2 on 2025-11-18 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0002_product_average_rating_product_total_reviews_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_type', models.CharField(choices=[('HIGH_VALUE', 'High Value'), ('REGULAR', 'Regular'), ('OCCASIONAL', 'Occasional'), ('NEW', 'New Customer')], default='NEW', max_length=20)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('favorite_categories', models.JSONField(default=list)),
                ('favorite_brands', models.JSONField(default=list)),
                ('last_purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_frequency', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='segment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_spent'],
            },
        ),
        migrations.CreateModel(
            name='ProductPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('period_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=10)),
                ('units_sold', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to='products.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to='products.productvariant')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-report_date', '-units_sold'],
                'indexes': [models.Index(fields=['-report_date', '-units_sold'], name='reports_pro_report__56dd2c_idx'), models.Index(fields=['product', '-report_date'], name='reports_pro_product_a6e9ab_idx')],
                'unique_together': {('product', 'variant', 'report_date', 'period_type', 'warehouse')},
            },
        ),
        migrations.CreateModel(
            name='ProductRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_bought_together', models.IntegerField(default=0)),
                ('confidence_score', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products_a', to='products.product')),
                ('product_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products_b', to='products.product')),
            ],
            options={
                'ordering': ['-times_bought_together'],
                'indexes': [models.Index(fields=['product_a', '-times_bought_together'], name='reports_pro_product_e148ca_idx')],
                'unique_together': {('product_a', 'product_b')},
            },
        ),
        migrations.CreateModel(
            name='ProductTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('total_units_sold', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('growth_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('trend_direction', models.CharField(default='STABLE', max_length=20)),
                ('is_seasonal', models.BooleanField(default=False)),
                ('peak_season', models.CharField(blank=True, max_length=100)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trends', to='products.product')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['product', '-year'], name='reports_pro_product_278128_idx'), models.Index(fields=['-year', '-total_revenue'], name='reports_pro_year_3fb357_idx')],
                'unique_together': {('product', 'year', 'quarter', 'month')},
            },
        ),
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=10)),
                ('report_date', models.DateField()),
                ('total_orders', models.IntegerField(default=0)),
                ('total_items_sold', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('new_customers', models.IntegerField(default=0)),
                ('returning_customers', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_reports', to='products.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_reports', to='products.category')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_reports', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-report_date', 'report_type'],
                'indexes': [models.Index(fields=['-report_date', 'report_type'], name='reports_sal_report__da384f_idx'), models.Index(fields=['warehouse'], name='reports_sal_warehou_f8fe31_idx')],
                'unique_together': {('report_type', 'report_date', 'warehouse', 'category', 'brand')},
            },
        ),
    ]
