# Generated by Django 5.2.2 on 2025-12-01 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_average_rating_product_total_reviews_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(choices=[('PERCENTAGE', 'Percentage Discount'), ('FIXED', 'Fixed Amount Discount'), ('BULK', 'Bulk/Volume Pricing'), ('BUNDLE', 'Bundle Deal')], max_length=20)),
                ('parameters', models.JSONField(default=dict)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='pricing_rules', to='products.category')),
                ('products', models.ManyToManyField(blank=True, related_name='pricing_rules', to='products.product')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
